name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "stg" ]
  pull_request:
    branches: [ "main", "stg" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Lint App
        run: npm run lint

  # NOTE: Connect this repository with your Vercel project or EAS for deployments.
